[project]
name = "easteregg-skia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bhargav Kulkarni", email = "bhargav.kulkarni1@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "altair[save]>=6.0.0",
    "playwright>=1.57.0",
    "pyrefly>=0.47.0",
    "scipy>=1.16.3",
    "skia-python>=138.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]

[tool.ruff]
lint.ignore = ["E741"]
line-length = 100

[tool.ruff.format]
quote-style = "single"

[tool.pyrefly]
project-includes = ['scripts/']
ignore-missing-imports = ["skia"]
