'ozon.ru' = 'ozon.ru'
'bbc.com' = 'bbc.com'
't.co' = 't.co'
'roku.com' = 'roku.com'
'twitch.tv' = 'twitch.tv'
'weather.com' = 'weather.com'
'oxylabs.io' = 'oxylabs.io'
'sciencedirect.com' = 'sciencedirect.com'
'researchgate.net' = 'researchgate.net'
'bbc.co.uk' = 'bbc.co.uk'
'gmail.com' = 'gmail.com'
'cpanel.net' = 'cpanel.net'
'android.com' = 'android.com'
'ubuntu.com' = 'ubuntu.com'
'sourceforge.net' = 'sourceforge.net'
'youtube-nocookie.com' = 'youtube-nocookie.com'
'triplinkintl.com' = 'triplinkintl.com'
'mit.edu' = 'mit.edu'
'canva.com' = 'canva.com'
'ebay.com' = 'ebay.com'
'doi.org' = 'doi.org'
'pki.goog' = 'pki.goog'
'hichina.com' = 'hichina.com'
't-online.de' = 't-online.de'
'nist.gov' = 'nist.gov'
'imdb.com' = 'imdb.com'
'miui.com' = 'miui.com'
'forter.com' = 'forter.com'
'who.int' = 'who.int'
'cisco.com' = 'cisco.com'
'stripe.com' = 'stripe.com'
'telegram.org' = 'telegram.org'
'linktr.ee' = 'linktr.ee'
'hubspot.com' = 'hubspot.com'
'doubleverify.com' = 'doubleverify.com'
'openai.com' = 'openai.com'
'booking.com' = 'booking.com'
'adsrvr.org' = 'adsrvr.org'
'wikimedia.org' = 'wikimedia.org'
'wildberries.ru' = 'wildberries.ru'
'salesforce.com' = 'salesforce.com'
'autodesk.com' = 'autodesk.com'
'launchpad.net' = 'launchpad.net'
'hp.com' = 'hp.com'
'springer.com' = 'springer.com'
'duckdns.org' = 'duckdns.org'
'tinyurl.com' = 'tinyurl.com'
'dropcatch.com' = 'dropcatch.com'
'samsungcloud.com' = 'samsungcloud.com'
'etsy.com' = 'etsy.com'
'reuters.com' = 'reuters.com'
'drom.ru' = 'drom.ru'
'ok.ru' = 'ok.ru'
'www.gov.uk' = 'www.gov.uk'
'afternic.com' = 'afternic.com'
'alibaba.com' = 'alibaba.com'
'dnsmadeeasy.com' = 'dnsmadeeasy.com'
'wiley.com' = 'wiley.com'
'ibm.com' = 'ibm.com'
'harvard.edu' = 'harvard.edu'
'nature.com' = 'nature.com'
'debian.org' = 'debian.org'
'mtgglobals.com' = 'mtgglobals.com'
'yandex.com' = 'yandex.com'
'php.net' = 'php.net'
'amazon.co.uk' = 'amazon.co.uk'
'launchdarkly.com' = 'launchdarkly.com'
'weibo.com' = 'weibo.com'
'slack.com' = 'slack.com'
'ea.com' = 'ea.com'
'issuu.com' = 'issuu.com'
'moe.video' = 'moe.video'
'gnu.org' = 'gnu.org'
'tradingview.com' = 'tradingview.com'
'mi.com' = 'mi.com'
'checkpoint.com' = 'checkpoint.com'
'ivi.ru' = 'ivi.ru'
'weebly.com' = 'weebly.com'
'cdc.gov' = 'cdc.gov'
'quickconnect.to' = 'quickconnect.to'
'un.org' = 'un.org'
'cnbc.com' = 'cnbc.com'
'trustpilot.com' = 'trustpilot.com'
'naver.com' = 'naver.com'
'aol.com' = 'aol.com'
'washingtonpost.com' = 'washingtonpost.com'
'wsj.com' = 'wsj.com'
'aliyun.com' = 'aliyun.com'
'dell.com' = 'dell.com'
'bilibili.com' = 'bilibili.com'
'dailymail.co.uk' = 'dailymail.co.uk'
'dailymotion.com' = 'dailymotion.com'
'stanford.edu' = 'stanford.edu'
'opendns.com' = 'opendns.com'
'bloomberg.com' = 'bloomberg.com'
'plesk.com' = 'plesk.com'
'nvidia.com' = 'nvidia.com'
'temu.com' = 'temu.com'
'adriver.ru' = 'adriver.ru'
'hcaptcha.com' = 'hcaptcha.com'
