'google.com' = 'google.com'
'gstatic.com' = 'gstatic.com'
'facebook.com' = 'facebook.com'
'cloudflare.com' = 'cloudflare.com'
'microsoft.com' = 'microsoft.com'
'googleapis.com' = 'googleapis.com'
'youtube.com' = 'youtube.com'
'mail.ru' = 'mail.ru'
'apple.com' = 'apple.com'
'instagram.com' = 'instagram.com'
'dzen.ru' = 'dzen.ru'
'twitter.com' = 'twitter.com'
'linkedin.com' = 'linkedin.com'
'googletagmanager.com' = 'googletagmanager.com'
'office.com' = 'office.com'
'amazon.com' = 'amazon.com'
'wikipedia.org' = 'wikipedia.org'
'github.com' = 'github.com'
'bing.com' = 'bing.com'
'digicert.com' = 'digicert.com'
'netflix.com' = 'netflix.com'
'chatgpt.com' = 'chatgpt.com'
'wordpress.org' = 'wordpress.org'
'skype.com' = 'skype.com'
'youtu.be' = 'youtu.be'
'pinterest.com' = 'pinterest.com'
'whatsapp.com' = 'whatsapp.com'
'gandi.net' = 'gandi.net'
'yahoo.com' = 'yahoo.com'
'x.com' = 'x.com'
'icloud.com' = 'icloud.com'
'hicloudcam.com' = 'hicloudcam.com'
'tiktok.com' = 'tiktok.com'
'msn.com' = 'msn.com'
'spotify.com' = 'spotify.com'
'adobe.com' = 'adobe.com'
'vimeo.com' = 'vimeo.com'
'ntp.org' = 'ntp.org'
'cloudflare.net' = 'cloudflare.net'
'telekom.de' = 'telekom.de'
'zoom.us' = 'zoom.us'
'wa.me' = 'wa.me'
'myfritz.net' = 'myfritz.net'
'roblox.com' = 'roblox.com'
'qq.com' = 'qq.com'
'baidu.com' = 'baidu.com'
'nginx.org' = 'nginx.org'
'opera.com' = 'opera.com'
'nic.ru' = 'nic.ru'
'samsung.com' = 'samsung.com'
'sentry.io' = 'sentry.io'
'mozilla.org' = 'mozilla.org'
'bit.ly' = 'bit.ly'
'wordpress.com' = 'wordpress.com'
'ui.com' = 'ui.com'
'reddit.com' = 'reddit.com'
'googleadservices.com' = 'googleadservices.com'
'discord.gg' = 'discord.gg'
'intuit.com' = 'intuit.com'
'criteo.com' = 'criteo.com'
't.me' = 't.me'
'vk.com' = 'vk.com'
'mailinabox.email' = 'mailinabox.email'
'europa.eu' = 'europa.eu'
'snapchat.com' = 'snapchat.com'
'f5.com' = 'f5.com'
'dns.google' = 'dns.google'
'dropbox.com' = 'dropbox.com'
'apache.org' = 'apache.org'
'kaspersky.com' = 'kaspersky.com'
'gravatar.com' = 'gravatar.com'
'nih.gov' = 'nih.gov'
'epicgames.com' = 'epicgames.com'
'xiaomi.com' = 'xiaomi.com'
'forms.gle' = 'forms.gle'
'archive.org' = 'archive.org'
'msftconnecttest.com' = 'msftconnecttest.com'
'godaddy.com' = 'godaddy.com'
'nytimes.com' = 'nytimes.com'
'tumblr.com' = 'tumblr.com'
'miit.gov.cn' = 'miit.gov.cn'
'applovin.com' = 'applovin.com'
'paypal.com' = 'paypal.com'
'shopify.com' = 'shopify.com'
'webex.com' = 'webex.com'
'discord.com' = 'discord.com'
'triplinkintl.com' = 'triplinkintl.com'
'reg.ru' = 'reg.ru'
'macromedia.com' = 'macromedia.com'
'flickr.com' = 'flickr.com'
'soundcloud.com' = 'soundcloud.com'
'example.com' = 'example.com'
'medium.com' = 'medium.com'
'w3.org' = 'w3.org'
'cnn.com' = 'cnn.com'
'theguardian.com' = 'theguardian.com'
'taboola.com' = 'taboola.com'
'avast.com' = 'avast.com'
'oracle.com' = 'oracle.com'
'forbes.com' = 'forbes.com'
